### ISSUE TITLE
ENH - I would like to use csv or json instead of xlsx files

### ISSUE THREAD

**Issue by asdf8601** [KikeM/degiro-wrapper#12]
Task description

* [ ] add soport to csv, json

## Keywords

* output
* files

**Comment by emvalbuena** [comment]
A solution I see to this is to dump the positions `xls` file when downloaded into a tempfile (easy in Python), process it and then save it to `json` / `csv`.

**Comment by asdf8601** [comment]
mmm this is because the code downloads an excel file direclty from degiro api?

**Comment by emvalbuena** [comment]
Yes.

**Comment by emvalbuena** [comment]
I have found the endpoint to get the `csv`: https://trader.degiro.nl/reporting/secure/v3/positionReport/csv?intAccount=YYYYYYYY&sessionId=XXXXXXX&country=ES&lang=es&toDate=21%2F04%2F2020
