### ISSUE TITLE
SUPPORT - what are derivatives in sandbox ?

### ISSUE THREAD

**Issue by asdf8601** [KikeM/degiro-wrapper#15]
There is a variable called DERIVATIVES, what is this?

```python
DERIVATIVES = ['ES0A02188001', 'ES0A02188050']
```

It is used in "Compute Performance" section.

```python
amount_long_df = amount_df.drop(columns=DERIVATIVES).copy()
```

**Comment by asdf8601** [comment]
I think that this is custom asset that you want to skip from the analysis. I thinks that we should have a general `sandbox.ipynb` without any of this variables. Just for quickstart. 

In order to have a general notebook we should remove:

* `position` folder reference used to store xls files.
* customs isins like `DERIVATIVES`
* benchmark `^IBEX`???

What do you think @KikeM ?

**Comment by emvalbuena** [comment]
Derivatives are two option positions I opened, but I didn't want to have a look at the performance of the long part of the portfolio with them. 

I agree with you, we could have a second notebook on how to perform more tailored analysis.
