### ISSUE TITLE
.py to .ipynb workflow

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/degiro-wrapper#25]
Working methodology to allow any user to work comfortably with `.py` and `.ipynb` files without forcing other users to use the same format. 

**Previous requirements**
* [Install jupytext](https://github.com/mwouts/jupytext#command-line-conversion) (add to `requirements-dev.txt`).

**Workflow**
The Notebook code is represented both in `.py` and `.ipynb` files. These are synced by jupytext.

1. Open the file format you wish to work on (`.py/.ipynb`).
1. Implement your changes.
1. Sync to the other format (`.ipynb/.py`):
    * If working from the notebook, simply save.
    * If working from the `.py`, use [jupytext CLI](https://github.com/mwouts/jupytext#command-line-conversion):
    ```bash
    jupytext --sync notebook.ipynb
    ```

@mmngreco @KikeM

**Comment by emvalbuena** [comment]
¿Se puede programar que se ejecute el CLI de jupytext antes de cualquier commit?

@mmngreco

**Comment by asdf8601** [comment]
Para eso deberiamos usar https://pre-commit.com/ o https://github.com/inishchith/autoenv

**Comment by emvalbuena** [comment]
Not relevant anymore.
