### ISSUE TITLE
Compute portfolio's daily returns

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/degiro-wrapper#3]
From the positions and the cashflows, compute for each day the portfolio's daily return. Then compute the total return by geometrical linking. 

* [x] Download sample data.
* [ ] Create class methods to collect them.
* [ ] Create valuator class to compute the returns.  

## Keywords

* valuation

**Comment by KikeM** [comment]
```mermaid

graph TD

cashflows --> EF[External flows]
EF --> Inflows
EF --> Outflows
cashflows --> DP[Positions flows]
DP --> Opt[Options Sett.]
DP --> Fut[Futures Sett.]
DP --> Div[Dividends ?]

subgraph Cash Evolution
Inflows --> DC
Outflows --> DC
Opt --> DC
Fut --> DC
Div --> DC
end

cashflows --> DC[Cash MtM]

DC -->|Shifted| CashRet[Cash Returns]
Cash --> CashRet
positions --> PostLong[Stocks PV]
positions --> PostOpt[Options PV]
positions --> Cash[Cash PV]
```

**Comment by KikeM** [comment]
![image](https://user-images.githubusercontent.com/14164486/77813193-ed84b200-70a6-11ea-8415-a2b37f3b928d.png)

**Comment by asdf8601** [comment]
With link to the editor


[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblxuY2FzaGZsb3dzIC0tPiBFRltFeHRlcm5hbCBmbG93c11cbkVGIC0tPiBJbmZsb3dzXG5FRiAtLT4gT3V0Zmxvd3NcbmNhc2hmbG93cyAtLT4gRFBbUG9zaXRpb25zIGZsb3dzXVxuRFAgLS0-IE9wdFtPcHRpb25zIFNldHQuXVxuRFAgLS0-IEZ1dFtGdXR1cmVzIFNldHQuXVxuRFAgLS0-IERpdltEaXZpZGVuZHMgP11cblxuc3ViZ3JhcGggQ2FzaCBFdm9sdXRpb25cbkluZmxvd3MgLS0-IERDXG5PdXRmbG93cyAtLT4gRENcbk9wdCAtLT4gRENcbkZ1dCAtLT4gRENcbkRpdiAtLT4gRENcbmVuZFxuXG5jYXNoZmxvd3MgLS0-IERDW0Nhc2ggTXRNXVxuXG5EQyAtLT58U2hpZnRlZHwgQ2FzaFJldFtDYXNoIFJldHVybnNdXG5DYXNoIC0tPiBDYXNoUmV0XG5wb3NpdGlvbnMgLS0-IFBvc3RMb25nW1N0b2NrcyBQVl1cbnBvc2l0aW9ucyAtLT4gUG9zdE9wdFtPcHRpb25zIFBWXVxucG9zaXRpb25zIC0tPiBDYXNoW0Nhc2ggUFZdIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblxuY2FzaGZsb3dzIC0tPiBFRltFeHRlcm5hbCBmbG93c11cbkVGIC0tPiBJbmZsb3dzXG5FRiAtLT4gT3V0Zmxvd3NcbmNhc2hmbG93cyAtLT4gRFBbUG9zaXRpb25zIGZsb3dzXVxuRFAgLS0-IE9wdFtPcHRpb25zIFNldHQuXVxuRFAgLS0-IEZ1dFtGdXR1cmVzIFNldHQuXVxuRFAgLS0-IERpdltEaXZpZGVuZHMgP11cblxuc3ViZ3JhcGggQ2FzaCBFdm9sdXRpb25cbkluZmxvd3MgLS0-IERDXG5PdXRmbG93cyAtLT4gRENcbk9wdCAtLT4gRENcbkZ1dCAtLT4gRENcbkRpdiAtLT4gRENcbmVuZFxuXG5jYXNoZmxvd3MgLS0-IERDW0Nhc2ggTXRNXVxuXG5EQyAtLT58U2hpZnRlZHwgQ2FzaFJldFtDYXNoIFJldHVybnNdXG5DYXNoIC0tPiBDYXNoUmV0XG5wb3NpdGlvbnMgLS0-IFBvc3RMb25nW1N0b2NrcyBQVl1cbnBvc2l0aW9ucyAtLT4gUG9zdE9wdFtPcHRpb25zIFBWXVxucG9zaXRpb25zIC0tPiBDYXNoW0Nhc2ggUFZdIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)
