### ISSUE TITLE
BUG: SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

### ISSUE THREAD

**Issue by Xylambda** [KikeM/degiro-wrapper#34]
When you run the notebook `notebooks/sandbox` for the first time in MacOS, it can happen that the necessary certificates are not installed, hence making the code crash when calling `download_positions` function.

### Problem

By running the notebook `sandbox` you will get the error.

### Error
`SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)`

### OS and Browser
 - MacOS 10.15.5. Catalina
 - Safari

**Comment by Xylambda** [comment]
The solution is pretty straightforward. You simply need to install the certificates. 

### Solution
1. Go to Macintosh HD.
2. Go to Python Folder
3. Run `Install Certificates.command` file.

You can now run the notebook without the SSL error.

**Comment by emvalbuena** [comment]
Hi @Xylambda,

Thanks for reporting the solution of the problem.

Are you using an environment manager such as conda or virtualenv?

**Comment by Xylambda** [comment]
I am using Conda to manage my environments.
