### ISSUE TITLE
ENH - Allow other languages

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/degiro-wrapper#4]
Currently only supports ES files. 
## Keywords

* valuation

**Comment by asdf8601** [comment]
This means speaking/writing language (not a programming language), isn't it?

**Comment by emvalbuena** [comment]
Yes, but I think I'll do it on "on demand basis", if any user runs into the project and can provide the headers in the downloaded files.

**Comment by emvalbuena** [comment]
I will close this issue for the moment, the only users have their data in spanish.
