### ISSUE TITLE
BUG: Product name is trimmed when database is created 

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/degiro-wrapper#40]
_To be completed_

**Describe the bug**

```
420                   ISHARES MSCI WOR A  IE00B4L5Y983
452   SPDR S&P 500 LOW VOLATILITY UCI...  IE00B802KR88
546   XTRACKERS II EUROZONE GOVERNMEN...  LU0290355717
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by asdf8601** [comment]
I think this is only on the DF's representation but real trimming, you can check this by slicing one value `df.iloc[452, 0]` it should return the whole string stored in that cell. 

If this is a problem, you may want to take a look to [pandas options](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#getting-and-setting-options), you can play with the `pd.set_option("max_colwidth", 50)` command or probably you will find something that fits better in the docs.

**Comment by emvalbuena** [comment]
You were right, I checked it last night and indeed the name is correctly stored.

Thanks!
