### ISSUE TITLE
CLN - Moves ipynb from src to notebooks folder

### ISSUE THREAD

**Issue by asdf8601** [KikeM/degiro-wrapper#5]
I suggest move notebooks from `src` to another folder (`notebook` maybe?) in order to modularize the code and make it easier to maintain and extend it. I see a notebook like an application which uses the source code (`src`).  What do you think @KikeM ?

**Comment by emvalbuena** [comment]
I like the idea. 

Would you build classes or it is not mature enough yet?

**Comment by asdf8601** [comment]
Well, I think that it could be a good idea prepare the skeleton first until add the API-OOP.

**Comment by emvalbuena** [comment]
Okey so I am working on this and I am running into problems to import the files from the notebooks.

I have read there are at least two good [solutions](https://stackoverflow.com/questions/49264194/import-py-file-in-another-directory-in-jupyter-notebook):
1. Add the path manually when loading the notebook (with `import sys` and all that).
1. Create a package (`setup.py`) and install it with the `-e` flag. 

I rather do the second one, what do you think @mmngreco ?

**Comment by asdf8601** [comment]
For now I will choose the first option and open another task to create a package in the future.

**Comment by emvalbuena** [comment]
I'll do so then ;)
