### ISSUE TITLE
BLD: Separate requirements.txt

### ISSUE THREAD

**Issue by asdf8601** [KikeM/degiro-wrapper#6]
Some requirements are not necessary to play whit this project. I suggest change it to something like this:

* `requirements-base.txt` : Contains the abstract libraries used in this project (without versions).
* `requirements-dev.txt` : Contains tools used by a developer (inside should have a reference to `requirements-test.txt` ?  ).
* `requirements-test.txt` : Contains libraries used for testing.
* `requirements.txt` : This is the usually version of a requirements, contains fixed versions to make this project run properly.

This can be useful to install only what we need.

**Comment by emvalbuena** [comment]
Should the `requirements-dev.txt` file have versions pinned?

**Comment by emvalbuena** [comment]
See https://github.com/KikeM/degiro-wrapper/tree/feature/requirements, I was already working on it ;)

**Comment by emvalbuena** [comment]
Interesting libraries to have as dependencies:

* http://pmorissette.github.io/ffn/index.html
* https://github.com/cuemacro/finmarketpy
* https://github.com/bfolkens/py-market-profile
* https://github.com/twopirllc/pandas-ta
