### ISSUE TITLE
create a CLI version of sandbox

### ISSUE THREAD

**Issue by asdf8601** [KikeM/degiro-wrapper#9]
It would be nice to have cli version of sandbox in order to do somthing like this:

```bash
$ degiro nav 
$ degiro report today 
$ degiro report ytd
$ degiro report all -o "report.xls"
$ degiro orders  # actives orders
$ degiro status
```

**Comment by emvalbuena** [comment]
Yes! That would be amazing. 

What are the outputs you would expect from each command?

**Comment by asdf8601** [comment]
We can think on that. What would you like to see there? I think more or less what sandbox does it would be nice (except the graphs).

for example:

```bash
$ degiro nav 
2020-03-25    70.3076
2020-03-26     70.302
2020-03-27    70.2991
```
